INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME) VALUES ('Czeslaw', 'Milosz');
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME) VALUES ('Witold', 'Gombrowicz');
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME) VALUES ('Adam', 'Mickiewicz');
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME) VALUES ('Henryk', 'Sienkiewicz');